src/css/custom.css

Before on Safari 15.4
After on Safari 15.4
Cause:
https://caniuse.com/?search=has

fix: remove css with `:has` as that breaks safari 15.4 and above

---

docs/configuration/pipeline-configuration-files.mdx

The CLI command for using config files is missing an 's'.

fix typo in pipeline configs example

---

docs/processors/builtin.mdx

This PR adds the user documentation for processors `encodewithschemakey`, `encodewithschemapayload`, `decodewithschemakey` and `decodewithschemapayload`.

Document schema registry processors

---

static/connectors.json

We don't have an auotmated CI action yet, so I regenerated `connectors.json` manually.

Regenerate connectors.json

---

docs/processors/referencing.mdx

The following Informational admonition in the Conduit docs has a broken link:
> Read more about how to register [standalone processors](https://conduit.io/docs/processors/standalone-processors) in Conduit.
Link should be https://conduit.io/docs/processors/standalone or https://conduit.io/docs/processors/standalone/how-it-works

fix: referenced standalone processor link is broken

---

docs/introduction/what-is-conduit.mdx
docs/processors/getting-started.mdx
docs/processors/referencing.mdx
docs/processors/standalone/building.mdx
docs/processors/standalone/how-it-works.mdx
docs/processors/standalone/index.mdx

This pull-request adds a new index page for processors that should give users a quick overview on how to use standalone processors in Conduit.
Part of https://github.com/ConduitIO/conduit/issues/1422

doc(processors): How to use standalone processors

---

README.md
docusaurus.config.ts

This page was removed in https://github.com/ConduitIO/conduit-site/pull/62. This PR removes the top link which currently sends shows a 404 page.

fix(guides): broken link

---

docs/introduction/getting-started.mdx
docs/running/binary.mdx
docusaurus.config.ts

Replaces `0.9.1` with `0.10.0`.

Conduit release v0.10.0

---

docs/processors/builtin/error.mdx
docs/processors/builtin/field.convert.mdx
docs/processors/builtin/field.exclude.mdx
docs/processors/builtin/field.rename.mdx
docs/processors/builtin/field.set.mdx
docs/processors/builtin/json.decode.mdx
docs/processors/builtin/json.encode.mdx
docs/processors/builtin/unwrap.debezium.mdx
docs/processors/builtin/unwrap.kafkaconnect.mdx
docs/processors/builtin/unwrap.opencdc.mdx
docs/processors/builtin/webhook.http.mdx
src/processorgen/main.go
src/processorgen/specs/error.json
src/processorgen/specs/webhook.http.json

Followup to https://github.com/ConduitIO/conduit/pull/1597 and https://github.com/ConduitIO/conduit/pull/1598.

Update processors docs

---

docs/introduction.mdx
docusaurus.config.ts

Architecture's page was moved on a previous PR and this link was outdated. Added a redirect just in case that was bookmarked.

fix: broken link

---

docs/connectors/additional-built-in-plugins.mdx
docs/connectors/connector-lifecycle.mdx
docs/connectors/kafka-connect-connector.mdx
docs/connectors/output-formats.mdx

This PR adds instructions for adding built-in connectors to Conduit. Even though the approach taken is embedding Conduit into a simple app, the goal of this guide isn't to provide comprehensive instructions for embedding Conduit (which is planned in https://github.com/ConduitIO/conduit/issues/1268).

Customize Conduit's built-in connectors

---

docs/processors/builtin/field.convert.mdx
src/processorgen/specs/field.convert.json

The only processor that changed is `field.convert`, this updates its spec and regenerates the documentation.

Update processor specs and regenerate docs

---

docs/processors/standalone/building.mdx

add docs for the Schemas access from processors, and the two Schema utility functions.

add schema utility functions to building.mdx

---

docs/features/dead-letter-queue.mdx

I corrected the numbers in the examples.

Clarify dead-letter queue behavior

---

docusaurus.config.ts

Now that we have a changelog we can link to it rather than to github.

Link banner to changelog

---

docs/2-developing/0-connectors/0-connectors.mdx
docs/2-developing/1-processors/index.mdx

Extracted from https://github.com/ConduitIO/conduit/blob/main/docs/writing-a-connector-guidelines.md. I'll update that document so it points out to [conduit.io/docs](https://conduit.io/docs).
Part of https://github.com/ConduitIO/conduit/issues/1919

doc: improve developing connectors

---

.gitignore
docs/1-using/6-other-features/1-schema-support.mdx
docs/2-developing/0-connectors/3-developing-source-connectors.mdx
docs/2-developing/0-connectors/4-developing-destination-connectors.mdx
src/connectorgen/README.md

Adds docs on how to add schema support on both source and destination connectors. I found out that the current docs don't say much about *how* to do this, so this PR should help.

Better schema docs

---

src/connectorgen/main.go
static/connectors.json

Test modules within the SDK use SDK as a dependency, so the SDK is included as a dependent of itself.

Exclude SDK from dependents

---

changelog/2025-03-20-conduit-0-13-3-release.mdx

fix: typo💂

---

docs/2-developing/1-processors/1-building.mdx

Fix minor syntax error on [Build Your Own Processor](https://conduit.io/docs/developing/processors/building)

fixing syntax on processor building page

---

docusaurus.config.ts

There used to be a link to the HTTP API, but it was accidentally removed as part of this pull-request: https://github.com/ConduitIO/conduit-site/pull/261/files#diff-cc8abb6104e21d495dc8f64639c7b03419226d920d1c545df51be9b0b73b2784L70.

fix: add http API link again

---

docs/0-what-is/1-core-concepts/0-architecture.mdx
docs/1-using/5-connectors/6-configuration-parameters/3-batching.mdx

This fixes cloudflare build (broken links) and add small tweaks to list mall heading options in the architecture page and adds an admonition to the different architectures to make it stand out.

fixes and suggestions
