docs/introduction/what-is-conduit.mdx

While the "next steps" at the bottom are helpful, not linking anywhere kind of defeats the purpose. 
Also, I reworded the intro paragraph since it seemed a little choppy.

add links to various Conduit channels

---

docs/connectors/_category_.json
docs/connectors/kafka-connect-wrapper/_category_.json
docs/connectors/kafka-connect-wrapper/overview.mdx

Here's a version of what we talked about.

initial version

---

docs/Deploy/aws_ec2.mdx

have too many wills

---

src/css/custom.css

Resolves https://github.com/ConduitIO/conduit-site/issues/17. Removes backticks from markdown displayed in the documentation.

Remove backticks for code

---

docs/connectors/connector-lifecycle.mdx
docs/introduction/getting-started.mdx
docs/pipeline-configuration-files/provisioning.mdx

This PR adds a document that describes the connector lifecycle + lifecycle events.
Closes https://github.com/ConduitIO/conduit/issues/957.

Connector lifecycle

---

docs/introduction/getting-started.mdx
docusaurus.config.js
src/pages/index.js

Updates the banner to reflect the new release.

Update banner for 0.8

---

docs/introduction/getting-started.mdx
docs/running/binary.mdx

Some leftovers from our recent 0.9.0 release.

fix: update to newer conduit version

---

docs/processors/how-to-build-standalone-processors.mdx

Felt bad for last minute suggestions, so I decided to open this other pull-request reflecting my suggestions. 
Branched of https://github.com/ConduitIO/conduit-site/pull/53

refactor: raul's suggestions

---

docs/processors/standalone/how-it-works.mdx
docs/processors/standalone/index.mdx
docs/processors/standalone/wasm.mdx
docusaurus.config.ts
package.json
yarn.lock

Part of https://github.com/ConduitIO/conduit/issues/1422.

Standalone processors under the hood (WASM)

---

docs/connectors/output-formats.mdx
docs/connectors/referencing.mdx
docs/features/dead-letter-queue.mdx
docs/introduction/getting-started.mdx
docs/pipeline-configuration-files/getting-started.mdx
docs/pipeline-configuration-files/specifications.mdx
docs/processors/getting-started.mdx
docs/processors/processor-concurrency.mdx
docs/processors/referencing.mdx

Part of https://github.com/ConduitIO/conduit/issues/1422

doc(processors): update getting started

---

docs/connectors/building.mdx

Closes https://github.com/ConduitIO/conduit/issues/866.

Document supported data types in standalone source connectors

---

docs/processors/standalone/building.mdx

Here are some improvements for our docs regarding building your own processor, specifically the "Specification" section was expanded to explain each field.

Improve page for building a processor

---

docs/processors/conditions.mdx

follow up of https://github.com/ConduitIO/conduit-site/pull/65

fix(processor): clearer statement

---

docs/processors/builtin/avro.decode.mdx
docs/processors/builtin/avro.encode.mdx
docs/processors/builtin/base64.decode.mdx
docs/processors/builtin/base64.encode.mdx
docs/processors/builtin/custom.javascript.mdx
docs/processors/builtin/field.convert.mdx
docs/processors/builtin/field.exclude.mdx
docs/processors/builtin/field.rename.mdx
docs/processors/builtin/field.set.mdx
docs/processors/builtin/filter.mdx
docs/processors/builtin/json.decode.mdx
docs/processors/builtin/json.encode.mdx
docs/processors/builtin/unwrap.debezium.mdx
docs/processors/builtin/unwrap.kafkaconnect.mdx
docs/processors/builtin/unwrap.opencdc.mdx
docs/processors/builtin/webhook.http.mdx
src/processorgen/main.go
src/processorgen/mdx.tmpl

This makes it possible to display the processor configuration as YAML in addition to the table we display now.

Display processor configuration as YAML

---

docs/processors/builtin/avro.decode.mdx
docs/processors/builtin/avro.encode.mdx
docs/processors/builtin/custom.javascript.mdx
docs/processors/builtin/webhook.http.mdx
src/processorgen/specs/avro.decode.json
src/processorgen/specs/avro.encode.json
src/processorgen/specs/custom.javascript.json
src/processorgen/specs/webhook.http.json

Regenerates processor docs from the updated processor specs.

Regenerate processor docs

---

docs/pipeline-configuration-files/specifications.mdx

Add field details to pipeline file specification

---

docs/features/dead-letter-queue.mdx
docs/features/metrics.mdx
docs/features/opencdc-record.mdx
docs/features/pipeline-semantics.mdx
docs/features/storage.mdx

@hariso This PR only sorts alphabetically the menu:
**before**
**after**

sort alphabetically

---

docs/getting-started/installing-and-running.mdx
docs/introduction.mdx
docusaurus.config.ts

noticed that the installation instructions still have v0.11.0 which wasn't stable, so updated to 0.11.1

update to v0.11.1 instead of 0.11.0

---

docs/connectors/configuration-parameters/schema-extraction.mdx

Fix yaml formatting in schema extraction example

---

docs/connectors/building-connectors/developing-destination-connectors.mdx
docs/connectors/building-connectors/developing-source-connectors.mdx

Updates the guides for writing developing connectors with fresh examples from the file connector.

Update guides for developing connectors

---

docs/connectors/configuration-parameters/schema-extraction.mdx

Adds clarification about these two parameters cc @justmisosoup 
[Demo in Slack](https://meroxa.slack.com/archives/C01ERTL0MJR/p1727853573991289?thread_ts=1727817524.823089&cid=C01ERTL0MJR)

doc: Update schema extraction page

---

docs/features/pipeline-recovery.mdx

fix the link to disabling pipeline recovery

---

docs/1-using/3-pipelines/index.mdx
docs/1-using/4-connectors/index.mdx
docs/1-using/5-processors/index.mdx
docs/1-using/7-guides/index.mdx
docusaurus.config.ts

Also add a redirect to a recently shared link via Discord.

feat: add index pages to all collapsible sections

---

docusaurus.config.ts

Original link referenced in https://github.com/ConduitIO/conduit/discussions/1724

fix: add redirect

---

docs/1-using/5-processors/2-conditions.mdx

the current example results in an error passing the yaml file

fix invalid example for processors conditions

---

docs/0-what-is/0-introduction.mdx
docs/0-what-is/1-getting-started.mdx

Closes https://github.com/ConduitIO/conduit-site/issues/181.

Update the getting started guide

---

docusaurus.config.ts

Thanks to https://github.com/meroxa/meroxa.com/issues/242

feat: update blog link to filter conduit posts

---

changelog/2022-01-21-conduit-0-1-0-release.md
docs/1-using/0-installing-and-running.mdx
docs/1-using/1-configuration.mdx
docs/1-using/3-pipelines/1-provisioning.mdx
docs/1-using/4-connectors/1-installing.mdx
docs/1-using/6-other-features/1-schema-support.mdx
docs/1-using/6-other-features/3-storage.mdx
docs/1-using/7-guides/build-generator-to-log-pipeline.mdx
docs/2-developing/0-connectors/5-using-a-custom-connector.mdx
docs/2-developing/1-processors/index.mdx

Part of https://github.com/ConduitIO/conduit/issues/2065.

docs: Conduit is run with conduit run and not with conduit anymore

---

docs/2-developing/0-connectors/3-connector-configuration.mdx

Closes https://github.com/ConduitIO/conduit-site/issues/177.

specgen: document dynamic maps and slices

---

changelog/2025-02-04-pipelines-exit-on-error.md

Fixes https://github.com/ConduitIO/conduit-site/issues/219

changelog: on `pipelines.exit-on-error` flag removal.

---

changelog/2025-02-06-conduit-0-13-1-release.mdx
docs/1-using/0-installing-and-running.mdx
docs/1-using/8-guides/build-generator-to-log-pipeline.mdx
docusaurus.config.ts

Part of https://github.com/ConduitIO/conduit/issues/2135.

chore: update conduit version

---

docs/0-what-is/1-getting-started.mdx
docs/1-using/1-configuration.mdx
docs/1-using/2-cli.mdx

mini fixes

---

src/connectorgen/registry.go
static/connectors.json

Add two repos to ignore list

---

changelog/2025-03-20-benchi-announcement.mdx

This adds a changelog for Benchi, similar to the blog post, but more concise.

Benchi announcement changelog

---

changelog/2025-05-06-rabbitmq-connector-0-3-0.mdx
changelog/2025-05-07-dynamodb-connector-0-3-0.mdx

Changelog for https://github.com/conduitio-labs/conduit-connector-dynamodb/releases/tag/v0.3.0.
Check out Discord for [more context](https://discord.com/channels/828680256877363200/933725823813451797/1369396960485969950).

changelog: DynamoDB 0.3.0

---

src/css/dark.css

Fixes https://github.com/ConduitIO/conduit-site/issues/282
**Before**
**After**

fix: Connector header on dark mode

---

changelog/2025-05-16-dynamodb-connector-0-3-1.mdx

https://github.com/conduitio-labs/conduit-connector-dynamodb/releases/tag/v0.3.1

changelog for dynamodb v0.3.1 release

---

docs/1-using/7-other-features/1-schema-support.mdx
docs/2-developing/0-connectors/0-connectors.mdx
docs/2-developing/0-connectors/3-connector-configuration.mdx

doc: about logging

---

changelog/2025-06-03-http-connector-0-4-0.mdx
changelog/2025-06-04-http-connector-0-4-0.mdx
docs/1-using/5-connectors/7-list/33-http.mdx
docs/1-using/5-connectors/7-list/5-postgres.mdx
static/connectors.json
static/connectors/github.com/ConduitIO/conduit-connector-postgres@v0.13.0/.metadata.yaml
static/connectors/github.com/ConduitIO/conduit-connector-postgres@v0.13.0/connector.yaml
static/connectors/github.com/conduitio-labs/conduit-connector-http@v0.4.0/.metadata.yaml
static/connectors/github.com/conduitio-labs/conduit-connector-http@v0.4.0/connector.yaml

the release: https://github.com/conduitio-labs/conduit-connector-http/releases/tag/v0.4.0

add a changelog for the http release v0.4.0

---

changelog/2025-06-03-postgres-connector-0-13-0.mdx

changelog: Postgres v0.13.0

---

docs/1-using/8-guides/build-ai-summarize-pipeline.mdx

Some suggestions for https://github.com/ConduitIO/conduit-site/pull/317

suggestions for #317

---

docs/1-using/8-guides/build-ai-summarize-pipeline.mdx
docs/1-using/8-guides/build-generator-to-log-pipeline.mdx

Added a new guide page with an AI tutorial

add conduit AI guide

---

docs/0-what-is/0-introduction.mdx

Feedback by @hariso: it feels redundant.

remove logo from /docs
